services:
  odhllm:
    build: .
    ports:
      - 8080:8080
    depends_on:
      my-cash-redis:
        condition: service_healthy

  my-cash-redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    volumes:
      - /home/ubuntu/redis:/data



